### ISSUE TITLE
easy_install of git-svn-helpers does not pull down elementtree

### ISSUE THREAD

**Issue by claytron** [tomster/git-svn-helpers#1]
Steps to reproduce

```
$ easy_install git-svn-helpers
$ gitify
Traceback (most recent call last):
  File "/Users/clayton/.virtualenvs/gitify/bin/gitify", line 7, in ?
    sys.exit(
  File "/Users/clayton/.virtualenvs/gitify/lib/python2.4/site-packages/setuptools-0.6c9-py2.4.egg/pkg_resources.py", line 277, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/clayton/.virtualenvs/gitify/lib/python2.4/site-packages/setuptools-0.6c9-py2.4.egg/pkg_resources.py", line 2180, in load_entry_point
    return ep.load()
  File "/Users/clayton/.virtualenvs/gitify/lib/python2.4/site-packages/setuptools-0.6c9-py2.4.egg/pkg_resources.py", line 1913, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/clayton/.virtualenvs/gitify/lib/python2.4/site-packages/git_svn_helpers-0.3b-py2.4.egg/gitsvnhelpers/gitify.py", line 7, in ?
    from utils import basename
  File "/Users/clayton/.virtualenvs/gitify/lib/python2.4/site-packages/git_svn_helpers-0.3b-py2.4.egg/gitsvnhelpers/utils.py", line 2, in ?
    from elementtree import ElementTree
ImportError: No module named elementtree
```

Once I easy_install'd `elementtree` everything was cool.

**Comment by tomster** [comment]
Thanks, again. Fixed on master.
